version: '3.2'

services:
  backend:
    # restart: always
    container_name: back
    command: gunicorn nth_backend.wsgi:application --bind 0.0.0.0:8000 --timeout 1800
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./server/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    env_file:
      - ./server/.env/dev.env

  frontend:
    # restart: always
    # command : npm start
    container_name: front
    build:
      context: ./client/
      dockerfile: Dockerfile
    # ports:
    #   - 3000:3000
    expose:
      - 3000
    volumes:
      - react_build:/react/build
    depends_on:
      - backend    

  certbot:
    container_name: cert_bot
    build:
      context: ./certbot
    expose:
      - 80

  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles
      - react_build:/usr/share/nginx/html

volumes:
  static_files:
  react_build:
