version: '3.2'

services:
  backend:
    # restart: always
    ports:
      - "8000:8000"
    container_name: back
    command: gunicorn nth_backend.wsgi:application --bind 0.0.0.0:8000 --timeout 1800
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - static_files:/user/src/app/staticfiles/
      - ./server/db.sqlite3:/user/src/app/db.sqlite3
  
    env_file:
      - ./server/.env/dev.env
 
#   nginx:
#     image: nginx:1.15-alpine
#     ports:
#       - "80:80"
#       - "443:443"
#     depends_on:
#       - backend
#     volumes:
#       - ./nginx/conf.d:/etc/nginx/conf.d/
#       - static_files:/home/app/staticfiles
#       - ./nginx/certbot/conf:/etc/letsencrypt
#       - ./nginx/certbot/www:/var/www/certbot
#     command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
#   certbot:
#     image: certbot/certbot
#     volumes:
#       - ./nginx/certbot/conf:/etc/letsencrypt
#       - ./nginx/certbot/www:/var/www/certbot
#     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_files:
