version: '3.2'

services:
  backend:
    restart: always
    container_name: back
    command: gunicorn nth_backend.wsgi:application --bind 0.0.0.0:8000 --timeout 1800
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    restart: always
    command : npm start
    container_name: front
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend    

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - backend
