version: '3.2'

services:
  backend:
    # restart: always
    container_name: back
    command: gunicorn nth_backend.wsgi:application --bind 0.0.0.0:8000 --timeout 1800
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - static_files:/user/src/app/staticfiles/
  
    env_file:
      - ./server/.env/dev.env
 

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  static_files:
